nmct.ba.cashlessproject.web/Controllers/OrganisationsController.cs
using nmct.ba.cashlessproject.classlibrary;
using nmct.ba.cashlessproject.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nmct.ba.cashlessproject.web.Controllers
{
    public class OrganisationsController : Controller
    {
        // GET: Organisations
        [Authorize]
        public ActionResult Index()
        {
            List<Organisation> orgs = OrganisationDA.GetOrganisations();
            return View(orgs);
        }

        // GET: Organisations/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            Organisation org = OrganisationDA.DecryptOrganisation(OrganisationDA.GetOrganisation(id));
            return View(org);
        }

        // GET: Organisations/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Organisations/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(Organisation dOrg)
        {
                Organisation org = OrganisationDA.EncryptOrganisation(dOrg);
                OrganisationDA.InsertOrganisation(org);
                OrganisationDA.MakeDB(dOrg);
                return RedirectToAction("Index");
        }

        // GET: Organisations/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            Organisation org = OrganisationDA.DecryptOrganisation(OrganisationDA.GetOrganisation(id));
            return View(org);
        }

        // POST: Organisations/Edit/5
        [HttpPost]
        [Authorize]
        public ActionResult Edit(Organisation dOrg, FormCollection collection)
        {
            Organisation org = OrganisationDA.EncryptOrganisation(dOrg);
            OrganisationDA.UpdateOrganisation(org);
            return RedirectToAction("Index");
        }

        // GET: Organisations/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            Organisation org = OrganisationDA.DecryptOrganisation(OrganisationDA.GetOrganisation(id));
            return View(org);
        }

        // POST: Organisations/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                OrganisationDA.DeleteOrganisation(id);
                return RedirectToAction("Index");
            }
            catch
            {
                Organisation org = OrganisationDA.DecryptOrganisation(OrganisationDA.GetOrganisation(id));
                return View(org);
            }
        }
    }
}

nmct.ba.cashlessproject.web/Controllers/RegisterController.cs
using nmct.ba.cashlessproject.classlibrary;
using nmct.ba.cashlessproject.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nmct.ba.cashlessproject.web.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        [Authorize]
        public ActionResult Index()
        {
            List<Register> regs = RegisterDA.GetRegisters();
            ViewBag.OrganisationRegisters = RegisterDA.GetOrganisationRegisters() as IEnumerable<OrganisationRegister>;
            ViewBag.UnusedRegisters = RegisterDA.GetUnusedRegisters() as IEnumerable<Register>;
            return View(regs);
        }

        

        // GET: Register/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            Register reg = RegisterDA.GetRegister(id);
            return View(reg);
        }

        // GET: Register/Create
        [Authorize]
        public ActionResult Create()
        {
            Register reg = new Register()
            {
                PurchaseDate = DateTime.Now,
                ExpiresDate = new DateTime(DateTime.Now.Year + 5, DateTime.Now.Month, DateTime.Now.Day, DateTime.Now.Hour, DateTime.Now.Minute, 0)
            };
            return View(reg);
        }

        // POST: Register/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(Register reg)
        {
            try
            {
                RegisterDA.InsertRegister(reg);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(reg);
            }
        }

        // GET: Register/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            Register reg = RegisterDA.GetRegister(id);
            return View(reg);
        }

        // POST: Register/Edit/5
        [HttpPost]
        [Authorize]
        public ActionResult Edit(Register reg, FormCollection collection)
        {
            try
            {
                RegisterDA.UpdateRegister(reg);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Register/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            Register reg = RegisterDA.GetRegister(id);
            return View(reg);
        }

        // POST: Register/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, FormCollection form)
        {
            try
            {
                RegisterDA.DeleteRegister(id);
                return RedirectToAction("Index");
            }
            catch
            {
                Register reg = RegisterDA.GetRegister(id);
                return View(reg);
            }
        }




        // GET: Register/Assign/5
        [Authorize]
        public ActionResult Assign(int id)
        {
            Register reg = RegisterDA.GetRegister(id);

            ViewBag.Organisations = new SelectList(OrganisationDA.GetOrganisations(), "ID", "OrganisationName");
            ViewBag.Register = reg;
            OrganisationRegister orgReg = new OrganisationRegister()
            {
                RegisterName = reg.RegisterName,
                RegisterID = reg.ID,
                Device = reg.Device,
                FromDate = DateTime.Now,
                UntilDate = reg.ExpiresDate
            };
            return View(orgReg);
        }

        // POST: Register/Assign/5
        [Authorize]
        [HttpPost]
        public ActionResult Assign(OrganisationRegister orgReg)
        {
            try
            {
                RegisterDA.AssignRegister(orgReg);
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Organisations = new SelectList(OrganisationDA.GetOrganisations(), "ID", "OrganisationName");
                return View(orgReg);
            }
        }

        // GET: Register/UnAssign/5
        [Authorize]
        public ActionResult UnAssign(int? regId)
        {
            if (regId == null) return RedirectToAction("Index");
            OrganisationRegister orgReg = RegisterDA.GetOrganisationRegister(regId.Value);
            return View(orgReg);
        }

        // POST: Register/UnAssign/5
        [HttpPost]
        [Authorize]
        public ActionResult UnAssign(int regId)
        {
            try
            {
                RegisterDA.UnAssignRegister(regId);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

    }
}

nmct.ba.cashlessproject.web/Views/Register/Assign.cshtml
@model nmct.ba.cashlessproject.classlibrary.OrganisationRegister

@{
    ViewBag.Title = "Assign";
}

<h2>Assign</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrganisationRegister</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RegisterID)

        <div class="form-group">
            @Html.LabelFor(model => model.RegisterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.RegisterName)
                @Html.EditorFor(model => model.RegisterName, new { htmlAttributes = new { @class = "form-control", @disabled = "" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Device, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Device)
                @Html.EditorFor(model => model.Device, new { htmlAttributes = new { @class = "form-control", @disabled = "yup" } })
            </div>
        </div>

        @{ SelectList orgs = ViewBag.Organisations; }
        <div class="form-group">
            @Html.Label("Organisation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.OrganisationID, orgs, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UntilDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UntilDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UntilDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
        jQuery.validator.methods["date"] = function (value, element) {
            var dateRegex = /^(0?[1-9]\/|[12]\d\/|3[01]\/){2}(19|20)\d\d\s?.*$/;
            return this.optional(element) || dateRegex.test(value);
        };
</script>
}

nmct.ba.cashlessproject.web/Views/Register/Create.cshtml
@model nmct.ba.cashlessproject.classlibrary.Register

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Register</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RegisterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegisterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegisterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Device, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Device, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Device, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } } )
                @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiresDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpiresDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiresDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        // mm/dd/yyyy is ok - dd/mm/yyyy niet
        // jQuery.validator.methods["date"] = function (value, element) { return true; }
        jQuery.validator.methods["date"] = function (value, element) {
            var dateRegex = /^(0?[1-9]\/|[12]\d\/|3[01]\/){2}(19|20)\d\d\s?.*$/;
            return this.optional(element) || dateRegex.test(value);
        };
    </script>

}

nmct.ba.cashlessproject.web/Views/Register/Delete.cshtml
@model nmct.ba.cashlessproject.classlibrary.Register

@{
    ViewBag.Title = "Delete";
}

<h2>Delete @Model.RegisterName</h2>

<ul class="nav nav-pills">
    <li><a href="/Register">&#171; List</a></li>
    <li>@Html.ActionLink("Details", "Details", new { id = Model.ID })<li>
    <li>@Html.ActionLink("Edit", "Edit", new { id = Model.ID })</li>
    <li class="active">@Html.ActionLink("Delete", "Delete", new { id = Model.ID })</li>
</ul>


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Register</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegisterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Device)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiresDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiresDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Cancel", "Index", new { }, new { @class = "btn btn-default" })
            <input type="submit" value="Delete" class="btn btn-primary" />
        </div>
    }
</div>

nmct.ba.cashlessproject.web/Views/Register/Details.cshtml
@model nmct.ba.cashlessproject.classlibrary.Register

@{
    ViewBag.Title = "Details";
}

<h2>@Model.RegisterName</h2>

<ul class="nav nav-pills">
    <li><a href="/Register">&#171; List</a></li>
    <li class="active">@Html.ActionLink("Details", "Details", new { id = Model.ID })<li>
    <li>@Html.ActionLink("Edit", "Edit", new { id = Model.ID })</li>
    <li>@Html.ActionLink("Delete", "Delete", new { id = Model.ID })</li>
</ul>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegisterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Device)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiresDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiresDate)
        </dd>

    </dl>
</div>

nmct.ba.cashlessproject.web/Views/Register/Edit.cshtml
@model nmct.ba.cashlessproject.classlibrary.Register

@{
    ViewBag.Title = "Edit";
}

<h2>Edit @Model.RegisterName</h2>

<ul class="nav nav-pills">
    <li><a href="/Register">&#171; List</a></li>
    <li>@Html.ActionLink("Details", "Details", new { id = Model.ID })</li>
    <li class="active">@Html.ActionLink("Edit", "Edit", new { id = Model.ID })</li>
    <li>@Html.ActionLink("Delete", "Delete", new { id = Model.ID })</li>
</ul>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Register</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.RegisterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegisterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegisterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Device, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Device, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Device, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiresDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpiresDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiresDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        // mm/dd/yyyy is ok - dd/mm/yyyy niet
        // jQuery.validator.methods["date"] = function (value, element) { return true; }
        jQuery.validator.methods["date"] = function (value, element) {
            var dateRegex = /^(0?[1-9]\/|[12]\d\/|3[01]\/){2}(19|20)\d\d\s?.*$/;
            return this.optional(element) || dateRegex.test(value);
        };
    </script>
}

nmct.ba.cashlessproject.web/Views/Register/Index.cshtml
@model IEnumerable<nmct.ba.cashlessproject.classlibrary.Register>

@{
    ViewBag.Title = "Registers";
}

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegisterName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Device)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpiresDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RegisterName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Device)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PurchaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpiresDate)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-link btn-xs" })
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-link btn-xs" })
            @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-link btn-xs" })
        </td>
    </tr>
}

</table>


<hr />

<h2>Unused Registers</h2>
@{ IEnumerable<nmct.ba.cashlessproject.classlibrary.Register> unreg = ViewBag.UnusedRegisters; }
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegisterName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Device)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpiresDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in unreg)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegisterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Device)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PurchaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpiresDate)
            </td>
            <td>
                @Html.ActionLink("Assign To Organisation", "Assign", new { id = item.ID }, new { @class = "btn btn-link btn-xs" })
            </td>
        </tr>
    }

</table>

<hr />

<h2>Used Registers</h2>

@{ IEnumerable<nmct.ba.cashlessproject.classlibrary.OrganisationRegister> orgreg = ViewBag.OrganisationRegisters; }
<table class="table table-striped">
    <tr>
        <th>Register</th>
        <th>Organisation</th>
        <th>From</th>
        <th>Until</th>
        <th></th>
    </tr>

@foreach (var item in orgreg) {
    <tr>
        <td>
            @Html.ActionLink(item.RegisterName, "Details", new { id = item.RegisterID })
        </td>
        <td>
            @Html.ActionLink(item.OrganisationName, "Details", "Organisations", new { id = item.OrganisationID }, new object { })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UntilDate)
        </td>
        <td>
            @Html.ActionLink("Unassign Register", "UnAssign", new { regId = item.RegisterID }, new { @class = "btn btn-link btn-xs" })
        </td>
    </tr>
}

</table>




@section Jumbotron {
    <div class="jumbotron" style="background-image: url('http://lorempixel.com/1900/300/business/');">
        <div class="container">
            <h1 class="head">Registers</h1>
            <p class="text-center head">
                @Html.ActionLink("Add Register", "Create", new { }, new { @class = "btn btn-primary" })
            </p>
        </div>
    </div>
}

nmct.ba.cashlessproject.web/Views/Register/UnAssign.cshtml
@model nmct.ba.cashlessproject.classlibrary.OrganisationRegister

@{
    ViewBag.Title = "UnAssign";
}

<h3>Are you sure you want to unassign @Model.RegisterName from @Model.OrganisationName?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrganisationID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganisationID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganisationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganisationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Device)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FromDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UntilDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UntilDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Cancel", "Index", new { }, new { @class = "btn btn-default" })
            <input type="submit" value="Delete" class="btn btn-primary" />
        </div>
    }
</div>